# Generated by Django 5.0.14 on 2026-03-24 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('id_number', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=20)),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('residential_address', models.TextField(blank=True)),
                ('email_address', models.EmailField(blank=True, max_length=254)),
                ('contact_number', models.CharField(max_length=20)),
                ('alternative_number', models.CharField(blank=True, max_length=20)),
                ('next_of_kin', models.CharField(blank=True, max_length=100)),
                ('relationship', models.CharField(blank=True, max_length=50)),
                ('next_of_kin_contact', models.CharField(blank=True, max_length=20)),
                ('employer_name', models.CharField(max_length=200)),
                ('position_held', models.CharField(max_length=100)),
                ('contract_type', models.CharField(default='Permanent', max_length=20)),
                ('employee_number', models.CharField(blank=True, max_length=50)),
                ('employment_date', models.DateField(blank=True, null=True)),
                ('contract_expiry_date', models.DateField(blank=True, null=True)),
                ('supervisor_name', models.CharField(blank=True, max_length=100)),
                ('supervisor_contact', models.CharField(blank=True, max_length=20)),
                ('employer_address', models.TextField(blank=True)),
                ('bank_name', models.CharField(max_length=100)),
                ('branch', models.CharField(blank=True, max_length=100)),
                ('account_number', models.CharField(max_length=30)),
                ('account_name', models.CharField(blank=True, max_length=100)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loan_installment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('repayment_period', models.IntegerField(default=1)),
                ('loan_purpose', models.CharField(blank=True, max_length=200)),
                ('id_document', models.FileField(upload_to='id_documents/')),
                ('proof_of_employment', models.FileField(upload_to='proof_of_employment/')),
                ('signature_image', models.TextField()),
                ('application_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
